use crate::Error;

#[derive(Clone, Copy, strum_macros::Display, Debug)]
#[strum(serialize_all = "lowercase")]
pub enum Language {
    English,
    Chinese,
    German,
    Spanish,
    Russian,
    Korean,
    French,
    Japanese,
    Portuguese,
    Turkish,
    Polish,
    Catalan,
    Dutch,
    Arabic,
    Swedish,
    Italian,
    Indonesian,
    Hindi,
    Finnish,
    Vietnamese,
    Hebrew,
    Ukrainian,
    Greek,
    Malay,
    Czech,
    Romanian,
    Danish,
    Hungarian,
    Tamil,
    Norwegian,
    Thai,
    Urdu,
    Croatian,
    Bulgarian,
    Lithuanian,
    Latin,
    Maori,
    Malayalam,
    Welsh,
    Slovak,
    Telugu,
    Persian,
    Latvian,
    Bengali,
    Serbian,
    Azerbaijani,
    Slovenian,
    Kannada,
    Estonian,
    Macedonian,
    Breton,
    Basque,
    Icelandic,
    Armenian,
    Nepali,
    Mongolian,
    Bosnian,
    Kazakh,
    Albanian,
    Swahili,
    Galician,
    Marathi,
    Punjabi,
    Sinhala,
    Khmer,
    Shona,
    Yoruba,
    Somali,
    Afrikaans,
    Occitan,
    Georgian,
    Belarusian,
    Tajik,
    Sindhi,
    Gujarati,
    Amharic,
    Yiddish,
    Lao,
    Uzbek,
    Faroese,
    #[strum(serialize = "haitian creole")]
    HaitianCreole,
    Pashto,
    Turkmen,
    Nynorsk,
    Maltese,
    Sanskrit,
    Luxembourgish,
    Myanmar,
    Tibetan,
    Tagalog,
    Malagasy,
    Assamese,
    Tatar,
    Hawaiian,
    Lingala,
    Hausa,
    Bashkir,
    Javanese,
    Sundanese,
}

impl TryFrom<&str> for Language {
    type Error = Error;

    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s.to_lowercase().trim() {
            "en" | "english" => Ok(Language::English),
            "zh" | "chinese" => Ok(Language::Chinese),
            "de" | "german" => Ok(Language::German),
            "es" | "spanish" => Ok(Language::Spanish),
            "ru" | "russian" => Ok(Language::Russian),
            "ko" | "korean" => Ok(Language::Korean),
            "fr" | "french" => Ok(Language::French),
            "ja" | "japanese" => Ok(Language::Japanese),
            "pt" | "portuguese" => Ok(Language::Portuguese),
            "tr" | "turkish" => Ok(Language::Turkish),
            "pl" | "polish" => Ok(Language::Polish),
            "ca" | "catalan" => Ok(Language::Catalan),
            "nl" | "dutch" => Ok(Language::Dutch),
            "ar" | "arabic" => Ok(Language::Arabic),
            "sv" | "swedish" => Ok(Language::Swedish),
            "it" | "italian" => Ok(Language::Italian),
            "id" | "indonesian" => Ok(Language::Indonesian),
            "hi" | "hindi" => Ok(Language::Hindi),
            "fi" | "finnish" => Ok(Language::Finnish),
            "vi" | "vietnamese" => Ok(Language::Vietnamese),
            "iw" | "hebrew" => Ok(Language::Hebrew),
            "uk" | "ukrainian" => Ok(Language::Ukrainian),
            "el" | "greek" => Ok(Language::Greek),
            "ms" | "malay" => Ok(Language::Malay),
            "cs" | "czech" => Ok(Language::Czech),
            "ro" | "romanian" => Ok(Language::Romanian),
            "da" | "danish" => Ok(Language::Danish),
            "hu" | "hungarian" => Ok(Language::Hungarian),
            "ta" | "tamil" => Ok(Language::Tamil),
            "no" | "norwegian" => Ok(Language::Norwegian),
            "th" | "thai" => Ok(Language::Thai),
            "ur" | "urdu" => Ok(Language::Urdu),
            "hr" | "croatian" => Ok(Language::Croatian),
            "bg" | "bulgarian" => Ok(Language::Bulgarian),
            "lt" | "lithuanian" => Ok(Language::Lithuanian),
            "la" | "latin" => Ok(Language::Latin),
            "mi" | "maori" => Ok(Language::Maori),
            "ml" | "malayalam" => Ok(Language::Malayalam),
            "cy" | "welsh" => Ok(Language::Welsh),
            "sk" | "slovak" => Ok(Language::Slovak),
            "te" | "telugu" => Ok(Language::Telugu),
            "fa" | "persian" => Ok(Language::Persian),
            "lv" | "latvian" => Ok(Language::Latvian),
            "bn" | "bengali" => Ok(Language::Bengali),
            "sr" | "serbian" => Ok(Language::Serbian),
            "az" | "azerbaijani" => Ok(Language::Azerbaijani),
            "sl" | "slovenian" => Ok(Language::Slovenian),
            "kn" | "kannada" => Ok(Language::Kannada),
            "et" | "estonian" => Ok(Language::Estonian),
            "mk" | "macedonian" => Ok(Language::Macedonian),
            "br" | "breton" => Ok(Language::Breton),
            "eu" | "basque" => Ok(Language::Basque),
            "is" | "icelandic" => Ok(Language::Icelandic),
            "hy" | "armenian" => Ok(Language::Armenian),
            "ne" | "nepali" => Ok(Language::Nepali),
            "mn" | "mongolian" => Ok(Language::Mongolian),
            "bs" | "bosnian" => Ok(Language::Bosnian),
            "kk" | "kazakh" => Ok(Language::Kazakh),
            "sq" | "albanian" => Ok(Language::Albanian),
            "sw" | "swahili" => Ok(Language::Swahili),
            "gl" | "galician" => Ok(Language::Galician),
            "mr" | "marathi" => Ok(Language::Marathi),
            "pa" | "punjabi" => Ok(Language::Punjabi),
            "si" | "sinhala" => Ok(Language::Sinhala),
            "km" | "khmer" => Ok(Language::Khmer),
            "sn" | "shona" => Ok(Language::Shona),
            "yo" | "yoruba" => Ok(Language::Yoruba),
            "so" | "somali" => Ok(Language::Somali),
            "af" | "afrikaans" => Ok(Language::Afrikaans),
            "oc" | "occitan" => Ok(Language::Occitan),
            "ka" | "georgian" => Ok(Language::Georgian),
            "be" | "belarusian" => Ok(Language::Belarusian),
            "tg" | "tajik" => Ok(Language::Tajik),
            "sd" | "sindhi" => Ok(Language::Sindhi),
            "gu" | "gujarati" => Ok(Language::Gujarati),
            "am" | "amharic" => Ok(Language::Amharic),
            "yi" | "yiddish" => Ok(Language::Yiddish),
            "lo" | "lao" => Ok(Language::Lao),
            "uz" | "uzbek" => Ok(Language::Uzbek),
            "fo" | "faroese" => Ok(Language::Faroese),
            "ht" | "haitian creole" => Ok(Language::HaitianCreole),
            "ps" | "pashto" => Ok(Language::Pashto),
            "tk" | "turkmen" => Ok(Language::Turkmen),
            "nn" | "nynorsk" => Ok(Language::Nynorsk),
            "mt" | "maltese" => Ok(Language::Maltese),
            "sa" | "sanskrit" => Ok(Language::Sanskrit),
            "lb" | "luxembourgish" => Ok(Language::Luxembourgish),
            "my" | "myanmar" => Ok(Language::Myanmar),
            "bo" | "tibetan" => Ok(Language::Tibetan),
            "tl" | "tagalog" => Ok(Language::Tagalog),
            "mg" | "malagasy" => Ok(Language::Malagasy),
            "as" | "assamese" => Ok(Language::Assamese),
            "tt" | "tatar" => Ok(Language::Tatar),
            "haw" | "hawaiian" => Ok(Language::Hawaiian),
            "ln" | "lingala" => Ok(Language::Lingala),
            "ha" | "hausa" => Ok(Language::Hausa),
            "ba" | "bashkir" => Ok(Language::Bashkir),
            "jw" | "javanese" => Ok(Language::Javanese),
            "su" | "sundanese" => Ok(Language::Sundanese),
            _ => Err(Error::InvalidLanguageString(s.to_string())),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::Language;

    #[test]
    fn language_to_string() {
        assert_eq!(Language::English.to_string(), "english");
        assert_eq!(Language::Japanese.to_string(), "japanese");
        assert_eq!(Language::HaitianCreole.to_string(), "haitian creole");
    }
}
